spring.application.name=notificationservice
server.port = 8082

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.topic.name=stock-topic
spring.kafka.consumer.group-id=notification
spring.kafka.consumer.auto-offset-reset=earliest

# Spring Kafka, "Exactly-Once" semantics (EOS)
# Consumer Configuration
# Isolation Level: Set isolation.level=read_committed. Without this, consumers may read messages from aborted or ongoing transactions.
# Manual Commits: Disable enable.auto.commit because the transaction manager will handle offset commits atomically with the production of new records.
spring.kafka.consumer.isolation-level=READ_COMMITTED
spring.kafka.consumer.enable-auto-commit=false