spring.application.name=stockservice
server.port = 8081

spring.kafka.consumer.bootstrap-servers= localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.topic.name=order-topic
spring.kafka.consumer.group-id=stock
spring.kafka.consumer.auto-offset-reset=earliest
# wait till 1kb (default 1 byte) data is accumulated in topic util maximum 100ms (default 500 ms) time.
# these are used to managed throughput and latency
spring.kafka.consumer.fetch-min-size= 1024
spring.kafka.consumer.fetch-max-wait=100

# Spring Kafka, "Exactly-Once" semantics (EOS)
# https://medium.com/threadsafe/exactly-once-processing-across-kafka-and-databases-using-kafka-transactions-idempotent-writes-09fe1f75bdab
# Consumer Configuration
# Isolation Level: Set isolation.level=read_committed. Without this, consumers may read messages from aborted or ongoing transactions.
# Manual Commits: Disable enable.auto.commit because the transaction manager will handle offset commits atomically with the production of new records.
spring.kafka.consumer.isolation-level=READ_COMMITTED
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.producer.topic.name=stock-topic
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.enable-idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.transaction-id-prefix=txn-order-processor
