spring.application.name= orderservice
server.port= 8080

spring.kafka.producer.bootstrap-servers= localhost:9092
spring.kafka.topic.name=order-topic
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Spring Kafka, "Exactly-Once" semantics (EOS)
# https://medium.com/threadsafe/exactly-once-processing-across-kafka-and-databases-using-kafka-transactions-idempotent-writes-09fe1f75bdab
# Producer Configuration
# To enable transactions at the producer level, you must provide a unique transactional.id and enable idempotence.
# Transactional ID: Must be unique for each producer instance to prevent "zombie" producers from interfering with active ones.
# Idempotence: Ensuring enable.idempotence=true (default in Kafka 3.0+) prevents duplicate writes caused by network retries.
spring.kafka.producer.properties.enable.idempotence = true
spring.kafka.producer.transaction-id-prefix=tx-order-
spring.kafka.producer.acks=all