spring.application.name= orderservice
server.port= 8080

spring.kafka.producer.bootstrap-servers= localhost:9092
spring.kafka.topic.name=order-topic
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# prevents the producer from sending duplicate messages if a network glitch occurs during an acknowledgment.
spring.kafka.producer.properties.enable.idempotence = true